### ISSUE TITLE
是否可以去掉对 athena-png-native 模块的依赖

### ISSUE THREAD

**Issue by Secbone** [o2team/athena#5]
我这边运行 serve 的时候发现抛出了一个错误，发现是 athena-png-native 模块最后一行抛出的，[详情](https://github.com/o2team/athena-png-native/blob/master/node-pngquant-native/binding.js#L66)

然后看了一下 athena 的引用，发现这个模块只有在[这里](https://github.com/o2team/athena/blob/53b3dfd868380912ba6e810a3b940020ba4b4871/lib/build/athena_mate/athena_imagemin.js#L11) 被引入过，并没有使用

所以这里是不是可以去掉这个依赖模块？

**Comment by luckyadam** [comment]
@Secbone 恩，这个模块是用来压缩png图片，这里还是用到了的，可否截下错误的截图看下~

**Comment by Secbone** [comment]
@luckyadam 

```
[18:35:44] 开始编译模块t-module！
[18:35:44] 开始扫描t-module模块所有文件！
undefined
Error: Can't load the addon. Issue to: https://github.com/xiangshouding/node-pngquant-native/issues
    at Object.<anonymous> (/usr/local/lib/node_modules/athena-html/node_modules/athena-png-native/node-pngquant-native/binding.js:66:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/athena-html/node_modules/athena-png-native/node-pngquant-native/index.js:1:77)
    at Module._compile (module.js:541:32)
[18:35:45] 预览t-module模块...
-------------------------------------
```

**Comment by Secbone** [comment]
等待支持 node V6 :)
