### ISSUE TITLE
增加对 node v7.x 的支持

### ISSUE THREAD

**Issue by Secbone** [o2team/athena#55]
```
[20:07:46] 开始编译模块live_cia！
[20:07:46] 开始扫描live_cia模块所有文件！
undefined
Error: Can't load the addon. Issue to: https://github.com/xiangshouding/node-pngquant-native/issues
    at Object.<anonymous> (/usr/local/lib/node_modules/athena-html/node_modules/athena-png-native/node-pngquant-native/binding.js:66:7)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/athena-html/node_modules/athena-png-native/node-pngquant-native/index.js:1:77)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
[20:07:46] 预览live_cia模块...
```

貌似是 `node-pngquant-native` 这个库的问题，没有往下追...

**Comment by luckyadam** [comment]
目前还没编译出对应node v7.x的包，暂待支持~

**Comment by luckyadam** [comment]
已支持，可以适配高版本的Node
