### ISSUE TITLE
无法初始化应用

### ISSUE THREAD

**Issue by chenkaixia** [o2team/athena#92]
版本：athena-html@1.4.16
出错命令：ath app
出错信息
  Allo xxxx! 我要开始创建项目了哟~
  need help? go and open issue: https://github.com/o2team/athena/issues/new
undefined:1
<!DOCTYPE HTML>
^
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/athena-html/lib/create/base.js:232:25)
    at Request.self.callback (/usr/local/lib/node_modules/athena-html/node_modules/request/request.js:187:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/athena-html/node_modules/request/request.js:1126:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/athena-html/node_modules/request/request.js:1046:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)

**Comment by cutPicturesMan** [comment]
+1
